services:
  sadtalker:
    build: ./sadtalker
    image: strifedeeno/ai-digital-twin-v2:sadtalker
    ports:
      - "7861:7860"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
      - ./results:/app/results # Mount results directory
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  chatterbox:
    build: 
      context: ./chatterbox
    image: strifedeeno/ai-digital-twin-v2:chatterbox
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]