version: "3.8"

services:
  ai-digital-twin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-digital-twin-v2
    volumes:
      - ./.env:/app/.env
      - ./models:/app/models
      - ./temp_audio:/app/temp_audio
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - /dev/snd:/dev/snd # For audio access
    # Audio support
    group_add:
      - audio
    privileged: true # May be required for proper audio device access
    network_mode: host # Use host networking for audio
    restart: unless-stopped