services:
  sadtalker:
    build: ./sadtalker
    image: strifedeeno/ai-digital-twin-v2:sadtalker
    ports:
      - "7861:7860"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
      - ./results:/app/results # Mount results directory
    # Explicit GPU request for non-Swarm docker compose
    # (deploy.resources.reservations.devices is ignored outside Swarm)
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  zonos:
    build:
      context: ./zonos
    image: strifedeeno/ai-digital-twin-v2:zonos
    ports:
      - "8090:8090"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
    # Ensure GPU visibility in regular docker compose mode
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=/root/.cache/huggingface
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
