services:
  kdtalker:
    build: ./kdtalker
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  zonos:
    build: ./zonos
    volumes:
      - ./data:/data # Existing volume for input/output
      - zonos_hf_cache:/root/.cache/huggingface/hub # Re-add volume for model cache
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  data: # Existing volume definition
  zonos_hf_cache: # Re-define the named volume for persistence