services:
  sadtalker:
    build: ./sadtalker
    ports:
      - "7861:7860"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
      - ./results:/app/results # Mount results directory
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  dia:
    build: 
      context: ./dia
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data # Mount data directory for input/output
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]