services:
  kdtalker:
    build: ./kdtalker
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  zonos:
    build: ./zonos
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  whisper:
    build: ./whisper
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  data: