[project]
authors = ["strifedeeno <coolarnay@gmail.com>"]
channels = [ "anaconda" ,"conda-forge"]
name = "AI-Digital-Twin-V2"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.13"
playsound = ">=1.3.0,<2"
openai = ">=1.60.1,<2"
pysoundfile = ">=0.11.0,<0.12"
python-dotenv = ">=0.21.0,<0.22"
speechrecognition = ">=3.10.4,<4"
numpy = ">=2.2.2,<3"
huggingface_hub = ">=0.29.2,<0.30"
pip = ">=25.0,<26"

[pypi-dependencies]
kokoro = ">=0.9.2, <0.10"
openai-whisper = ">=20240930, <20240931"
pyobjc = ">=11.0, <12"
pyaudio = ">=0.2.14, <0.3"
